# -*- coding: utf-8 -*-
"""Speech_Denoising_DSP_vs_LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uRKPwO1EMoDMBT4wU91V2sq1yBoD74yU
"""

from google.colab import files
uploaded = files.upload()

import os
print(os.listdir('/content'))

import numpy as np
import librosa
import matplotlib.pyplot as plt

file_path = "/content/sa1.wav"   # uploaded file

speech, fs = librosa.load(file_path, sr=16000)
speech = speech / np.max(np.abs(speech))  # normalize

print("Sampling rate:", fs)
print("Signal length:", speech.shape)

plt.figure(figsize=(12,4))
plt.plot(speech)
plt.title("Clean Speech Signal (SA1)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

def add_colored_noise(signal, snr_db):
    white = np.random.randn(len(signal))

    # AR(1) colored noise
    colored = np.convolve(white, [1, -0.9], mode='same')
    colored /= np.sqrt(np.mean(colored**2))

    signal_power = np.mean(signal**2)
    noise_power = signal_power / (10**(snr_db/10))

    noisy = signal + np.sqrt(noise_power) * colored
    return noisy, np.sqrt(noise_power) * colored


noisy_speech, noise = add_colored_noise(speech, snr_db=5)
noise_ref = np.convolve(noise, [1, 0.5], mode='same')


plt.figure(figsize=(12,4))
plt.plot(speech, label="Clean Speech")
plt.plot(noisy_speech, label="Noisy Speech (5 dB)", alpha=0.7)
plt.legend()
plt.grid()
plt.show()

def calculate_snr(clean, test):
    noise = test - clean
    return 10 * np.log10(np.mean(clean**2) / np.mean(noise**2))
print("SNR before filtering (dB):", calculate_snr(speech, noisy_speech))

def plot_fft(signal, fs, label):
    fft = np.abs(np.fft.rfft(signal))
    freqs = np.fft.rfftfreq(len(signal), 1/fs)
    plt.plot(freqs, fft, label=label)

plt.figure(figsize=(12,4))
plot_fft(speech, fs, "Clean")
plot_fft(noisy_speech, fs, "Noisy")
plt.legend()
plt.grid()
plt.show()

plt.figure(figsize=(12,4))
plt.specgram(noisy_speech, Fs=fs, NFFT=256, noverlap=128)
plt.colorbar(label="Intensity (dB)")
plt.title("Spectrogram of Noisy Speech")
plt.show()

def nlms_filter(primary, reference, mu=0.8, L=64, eps=1e-6):
    N = len(primary)
    w = np.zeros(L)
    y = np.zeros(N)
    e = np.zeros(N)

    for n in range(L, N):
        x = reference[n-L:n][::-1]
        y[n] = np.dot(w, x)
        e[n] = primary[n] - y[n]

        norm = np.dot(x, x) + eps
        w += (mu / norm) * e[n] * x

    return e

denoised_nlms = nlms_filter(noisy_speech, noise_ref)


plt.figure(figsize=(12,4))
plt.plot(speech, label="Clean")
plt.plot(noisy_speech, label="Noisy", alpha=0.4)
plt.plot(denoised_nlms, label="NLMS Denoised", linewidth=2)
plt.legend()
plt.grid()
plt.show()

snr_after = calculate_snr(speech, denoised_nlms)

print("SNR after NLMS (dB):", snr_after)
print("SNR Improvement (dB):", snr_after - calculate_snr(speech, noisy_speech))


def plot_fft(signal, fs, label):
    fft = np.abs(np.fft.rfft(signal))
    freqs = np.fft.rfftfreq(len(signal), 1/fs)
    plt.plot(freqs, fft, label=label)

plt.figure(figsize=(12,4))
plot_fft(noisy_speech, fs, "Noisy")
plot_fft(denoised_nlms, fs, "NLMS Denoised")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Magnitude")
plt.legend()
plt.grid()
plt.show()

# weiner filter with AWGN
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
def add_awgn(signal, snr_db):
    signal_power = np.mean(signal**2)
    noise_power = signal_power / (10**(snr_db / 10))
    noise = np.sqrt(noise_power) * np.random.randn(len(signal))
    return signal + noise
def calculate_snr(clean, noisy):
    noise = noisy - clean
    return 10 * np.log10(np.mean(clean**2) / np.mean(noise**2))
def wiener_filter(noisy, clean, fs, n_fft=512, hop=256):
    Y = librosa.stft(noisy, n_fft=n_fft, hop_length=hop)
    S = librosa.stft(clean, n_fft=n_fft, hop_length=hop)

    Ps = np.mean(np.abs(S)**2, axis=1, keepdims=True)
    Pn = np.mean(np.abs(Y - S)**2, axis=1, keepdims=True)

    H = Ps / (Ps + Pn + 1e-10)

    Y_hat = H * Y
    return librosa.istft(Y_hat, hop_length=hop)
speech, fs = librosa.load("/content/sa1.wav", sr=16000)
speech = speech / np.max(np.abs(speech))
snr_inputs = [-5, 0, 5, 10, 15]

snr_before_list = []
snr_after_list = []
snr_improvement_list = []

for snr in snr_inputs:
    noisy = add_awgn(speech, snr)
    denoised = wiener_filter(noisy, speech, fs)

    min_len = min(len(speech), len(denoised))
    clean = speech[:min_len]
    noisy = noisy[:min_len]
    denoised = denoised[:min_len]

    snr_before = calculate_snr(clean, noisy)
    snr_after = calculate_snr(clean, denoised)

    snr_before_list.append(snr_before)
    snr_after_list.append(snr_after)
    snr_improvement_list.append(snr_after - snr_before)

    print(f"SNR in: {snr_before:.2f} dB | SNR out: {snr_after:.2f} dB")

plt.figure(figsize=(12,4))
plt.plot(clean, label="Clean")
plt.plot(noisy, label="Noisy", alpha=0.5)
plt.plot(denoised, label="Wiener Denoised", linewidth=2)
plt.legend()
plt.title("Time-Domain Speech Enhancement (Wiener Filter)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

def plot_fft(sig, fs, label):
    fft = np.abs(np.fft.rfft(sig))
    freq = np.fft.rfftfreq(len(sig), 1/fs)
    plt.plot(freq, fft, label=label)

plt.figure(figsize=(12,4))
plot_fft(clean, fs, "Clean")
plot_fft(noisy, fs, "Noisy")
plot_fft(denoised, fs, "Wiener Denoised")
plt.legend()
plt.title("FFT Magnitude Comparison")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Magnitude")
plt.grid()
plt.show()

plt.figure(figsize=(12,4))
plt.specgram(noisy, Fs=fs, NFFT=256, noverlap=128)
plt.title("Spectrogram – Noisy Speech")
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.colorbar()
plt.show()

plt.figure(figsize=(12,4))
plt.specgram(denoised, Fs=fs, NFFT=256, noverlap=128)
plt.title("Spectrogram – Wiener Filter Output")
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.colorbar()
plt.show()

plt.figure(figsize=(7,5))
plt.plot(snr_before_list, snr_after_list, marker='o')
plt.xlabel("Input SNR (dB)")
plt.ylabel("Output SNR (dB)")
plt.title("Input SNR vs Output SNR (Wiener Filter)")
plt.grid()
plt.show()

plt.figure(figsize=(7,5))
plt.plot(snr_before_list, snr_improvement_list, marker='o')
plt.xlabel("Input SNR (dB)")
plt.ylabel("SNR Improvement (dB)")
plt.title("Input SNR vs SNR Improvement")
plt.grid()
plt.show()

#WF WITH BABBLE NOISE
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt
def calculate_snr(clean, noisy):
    noise = noisy - clean
    return 10 * np.log10(np.mean(clean**2) / np.mean(noise**2))
def add_babble_noise(clean, babble, snr_db):
    # Repeat babble if shorter than clean speech
    if len(babble) < len(clean):
        babble = np.tile(babble, int(np.ceil(len(clean) / len(babble))))

    babble = babble[:len(clean)]

    clean_power = np.mean(clean**2)
    noise_power = np.mean(babble**2)

    scale = np.sqrt(clean_power / (noise_power * 10**(snr_db / 10)))
    noisy = clean + scale * babble

    return noisy
def wiener_filter(noisy, clean, fs, n_fft=512, hop=256):
    Y = librosa.stft(noisy, n_fft=n_fft, hop_length=hop)
    S = librosa.stft(clean, n_fft=n_fft, hop_length=hop)

    Ps = np.mean(np.abs(S)**2, axis=1, keepdims=True)
    Pn = np.mean(np.abs(Y - S)**2, axis=1, keepdims=True)

    H = Ps / (Ps + Pn + 1e-10)

    Y_hat = H * Y
    return librosa.istft(Y_hat, hop_length=hop)
speech, fs = librosa.load("/content/sa1.wav", sr=16000)
speech = speech / np.max(np.abs(speech))
babble, _ = librosa.load("/content/baby-cooing-06.wav", sr=fs)
babble = babble / np.max(np.abs(babble))
snr_inputs = [-5, 0, 5, 10]

snr_before_list = []
snr_after_list = []
snr_improvement_list = []
for snr in snr_inputs:
    noisy = add_babble_noise(speech, babble, snr)
    denoised = wiener_filter(noisy, speech, fs)

    min_len = min(len(speech), len(denoised))
    clean = speech[:min_len]
    noisy = noisy[:min_len]
    denoised = denoised[:min_len]

    snr_before = calculate_snr(clean, noisy)
    snr_after = calculate_snr(clean, denoised)

    snr_before_list.append(snr_before)
    snr_after_list.append(snr_after)
    snr_improvement_list.append(snr_after - snr_before)

    print(f"Input SNR: {snr_before:.2f} dB | Output SNR: {snr_after:.2f} dB")
plt.figure(figsize=(12,4))
plt.plot(clean, label="Clean")
plt.plot(noisy, label="Noisy (Babble)", alpha=0.5)
plt.plot(denoised, label="Wiener Denoised", linewidth=2)
plt.legend()
plt.title("Time-Domain Speech Enhancement (Babble Noise)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()
def plot_fft(signal, fs, label):
    fft = np.abs(np.fft.rfft(signal))
    freq = np.fft.rfftfreq(len(signal), 1/fs)
    plt.plot(freq, fft, label=label)

plt.figure(figsize=(12,4))
plot_fft(clean, fs, "Clean")
plot_fft(noisy, fs, "Noisy (Babble)")
plot_fft(denoised, fs, "Wiener Denoised")
plt.legend()
plt.title("FFT Magnitude Comparison (Babble Noise)")
plt.xlabel("Frequency (Hz)")
plt.ylabel("Magnitude")
plt.grid()
plt.show()
plt.figure(figsize=(12,4))
plt.specgram(noisy, Fs=fs, NFFT=256, noverlap=128)
plt.title("Spectrogram – Noisy Speech (Babble)")
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.colorbar()
plt.show()

plt.figure(figsize=(12,4))
plt.specgram(denoised, Fs=fs, NFFT=256, noverlap=128)
plt.title("Spectrogram – Wiener Output (Babble)")
plt.xlabel("Time")
plt.ylabel("Frequency")
plt.colorbar()
plt.show()
plt.figure(figsize=(7,5))
plt.plot(snr_before_list, snr_after_list, marker='o')
plt.xlabel("Input SNR (dB)")
plt.ylabel("Output SNR (dB)")
plt.title("Input vs Output SNR (Babble Noise)")
plt.grid()
plt.show()
plt.figure(figsize=(7,5))
plt.plot(snr_before_list, snr_improvement_list, marker='o')
plt.xlabel("Input SNR (dB)")
plt.ylabel("SNR Improvement (dB)")
plt.title("SNR Improvement vs Input SNR (Babble Noise)")
plt.grid()
plt.show()

import os
import shutil

# Create folders
os.makedirs("/content/speech_clean", exist_ok=True)
os.makedirs("/content/noise", exist_ok=True)
os.makedirs("/content/output", exist_ok=True)

print("Folders created")

# Move TIMIT speech files (si, sx)
for file in os.listdir("/content"):
    fname = file.lower()
    if fname.endswith(".wav") and (fname.startswith("sa") or fname.startswith("si") or fname.startswith("sx")):
        shutil.move(f"/content/{file}", f"/content/speech_clean/{file}")

for file in os.listdir("/content"):
    if file.lower().endswith(".wav") and "8000" in file.lower():
        shutil.move(f"/content/{file}", f"/content/noise/{file}")


print("Speech and noise files moved successfully")

print("Clean speech files:")
print(os.listdir("/content/speech_clean"))

print("\nNoise files:")
print(os.listdir("/content/noise"))

import os
import numpy as np
import librosa
import librosa.display
import matplotlib.pyplot as plt

# Global parameters
FS = 16000          # Sampling frequency (Hz)
EPS = 1e-8          # Small value to avoid division by zero

# Paths
SPEECH_DIR = "/content/speech_clean"
NOISE_DIR = "/content/noise"
OUTPUT_DIR = "/content/output"

print("Number of clean speech files:", len(os.listdir(SPEECH_DIR)))
print("Number of noise files:", len(os.listdir(NOISE_DIR)))

# Pick one speech file
speech_files = sorted(os.listdir(SPEECH_DIR))
speech_path = os.path.join(SPEECH_DIR, speech_files[0])

speech, fs = librosa.load(speech_path, sr=FS)

# Normalize speech
speech = speech / np.max(np.abs(speech) + EPS)

print("Speech file:", speech_files[0])
print("Sampling rate:", fs)
print("Duration (seconds):", len(speech)/fs)

plt.figure(figsize=(12, 3))
plt.plot(speech)
plt.title("Clean Speech Signal (Time Domain)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

#SPECTROGRAM
plt.figure(figsize=(10, 4))
librosa.display.specshow(
    librosa.amplitude_to_db(np.abs(librosa.stft(speech)), ref=np.max),
    sr=FS,
    hop_length=256,
    x_axis='time',
    y_axis='hz'
)
plt.colorbar(label="Magnitude (dB)")
plt.title("Clean Speech Spectrogram")
plt.tight_layout()
plt.show()

# Pick one noise file
noise_files = sorted(os.listdir(NOISE_DIR))
noise_path = os.path.join(NOISE_DIR, noise_files[0])

noise, fs_n = librosa.load(noise_path, sr=FS)

# Normalize noise
noise = noise / np.max(np.abs(noise) + EPS)

print("Noise file:", noise_files[0])
print("Sampling rate:", fs_n)
print("Noise duration (seconds):", len(noise)/fs_n)

plt.figure(figsize=(12, 3))
plt.plot(noise)
plt.title("Noise Signal (Time Domain)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

#SPECTROGRAM OF NOISE
plt.figure(figsize=(10, 4))
librosa.display.specshow(
    librosa.amplitude_to_db(np.abs(librosa.stft(noise)), ref=np.max),
    sr=FS,
    hop_length=256,
    x_axis='time',
    y_axis='hz'
)
plt.colorbar(label="Magnitude (dB)")
plt.title("Noise Spectrogram")
plt.tight_layout()
plt.show()

def match_length(noise, target_len):
    if len(noise) >= target_len:
        return noise[:target_len]
    else:
        repeat_factor = int(np.ceil(target_len / len(noise)))
        noise = np.tile(noise, repeat_factor)
        return noise[:target_len]

noise_matched = match_length(noise, len(speech))

print("Speech length:", len(speech))
print("Noise length after matching:", len(noise_matched))

def mix_speech_noise(clean, noise, snr_db):
    # Power of clean speech
    speech_power = np.mean(clean**2)

    # Power of noise
    noise_power = np.mean(noise**2)

    # Required noise power for given SNR
    target_noise_power = speech_power / (10**(snr_db / 10))

    # Scale noise
    noise_scaled = noise * np.sqrt(target_noise_power / (noise_power + EPS))

    # Mix
    noisy = clean + noise_scaled

    return noisy, noise_scaled

SNR_DB = 5  # change this to -5, 0, 5, 10 later

noisy_speech, noise_scaled = mix_speech_noise(
    speech,
    noise_matched,
    SNR_DB
)

print(f"Created noisy speech at {SNR_DB} dB SNR")

def calculate_snr(clean, noisy):
    noise = noisy - clean
    return 10 * np.log10(
        np.mean(clean**2) / (np.mean(noise**2) + EPS)
    )

measured_snr = calculate_snr(speech, noisy_speech)
print("Measured SNR (dB):", measured_snr)


plt.figure(figsize=(12, 3))
plt.plot(speech, label="Clean")
plt.plot(noisy_speech, label=f"Noisy ({SNR_DB} dB)", alpha=0.7)
plt.legend()
plt.title("Clean vs Noisy Speech (Time Domain)")
plt.xlabel("Samples")
plt.ylabel("Amplitude")
plt.grid()
plt.show()

#spectrogram comparison
plt.figure(figsize=(12, 4))

plt.subplot(1, 2, 1)
librosa.display.specshow(
    librosa.amplitude_to_db(np.abs(librosa.stft(speech)), ref=np.max),
    sr=FS,
    hop_length=256,
    x_axis='time',
    y_axis='hz'
)
plt.title("Clean Speech")
plt.colorbar()

plt.subplot(1, 2, 2)
librosa.display.specshow(
    librosa.amplitude_to_db(np.abs(librosa.stft(noisy_speech)), ref=np.max),
    sr=FS,
    hop_length=256,
    x_axis='time',
    y_axis='hz'
)
plt.title(f"Noisy Speech ({SNR_DB} dB)")
plt.colorbar()

plt.tight_layout()
plt.show()

#DATASET GENERATORS

import os
import numpy as np
import librosa
import tensorflow as tf
SR = 8000          # Sampling rate
N_FFT = 256        # FFT size
HOP_LENGTH = 128   # Overlap
SEGMENT_LEN = SR * 1  # 1 second segments
SNR_RANGE = [-5, 0, 5, 10]
def load_audio(file_path, length=SEGMENT_LEN):
    audio, _ = librosa.load(file_path, sr=SR)

    if len(audio) < length:
        audio = np.pad(audio, (0, length - len(audio)))
    else:
        start = np.random.randint(0, len(audio) - length)
        audio = audio[start:start + length]

    return audio
def add_noise(clean, noise, snr_db):
    clean_power = np.mean(clean**2)
    noise_power = np.mean(noise**2)

    snr_linear = 10 ** (snr_db / 10)
    scaling_factor = np.sqrt(clean_power / (snr_linear * noise_power))

    return clean + scaling_factor * noise
def to_spectrogram(signal):
    spec = librosa.stft(signal, n_fft=N_FFT, hop_length=HOP_LENGTH)
    mag = np.abs(spec)
    log_mag = np.log1p(mag)
    return log_mag
speech_files = [f"/content/speech_clean/{f}"
                for f in os.listdir("/content/speech_clean")]

noise_files = [f"/content/noise/{f}"
               for f in os.listdir("/content/noise")]

print("Speech files:", len(speech_files))
print("Noise files:", len(noise_files))

def dataset_generator():
    while True:
        speech_path = np.random.choice(speech_files)
        noise_path = np.random.choice(noise_files)
        snr = np.random.choice(SNR_RANGE)

        clean = load_audio(speech_path)
        noise = load_audio(noise_path)

        noisy = add_noise(clean, noise, snr)

        clean_spec = to_spectrogram(clean)
        noisy_spec = to_spectrogram(noisy)

        yield noisy_spec[..., np.newaxis], clean_spec[..., np.newaxis]

#TENSORFLOW DATASET
BATCH_SIZE = 8

train_ds = tf.data.Dataset.from_generator(
    dataset_generator,
    output_signature=(
        tf.TensorSpec(shape=(129, None, 1), dtype=tf.float32),
        tf.TensorSpec(shape=(129, None, 1), dtype=tf.float32),
    )
)

train_ds = train_ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)

for noisy_spec, clean_spec in train_ds.take(1):
    print("Noisy shape:", noisy_spec.shape)
    print("Clean shape:", clean_spec.shape)

#CNN MODEL
from tensorflow.keras import layers, models

model = models.Sequential([
    layers.Input(shape=(129, None, 1)),

    layers.Conv2D(16, (3,3), padding="same", activation="relu"),
    layers.Conv2D(32, (3,3), padding="same", activation="relu"),
    layers.Conv2D(16, (3,3), padding="same", activation="relu"),

    layers.Conv2D(1, (3,3), padding="same", activation="linear")
])

model.compile(
    optimizer="adam",
    loss="mse"
)

model.summary()

history = model.fit(
    train_ds,
    steps_per_epoch=50,
    epochs=10
)

#INFERENCE
import matplotlib.pyplot as plt

# Make sure calculate_snr is defined
def calculate_snr(clean, noisy):
    power_clean = np.sum(clean**2)
    power_noise = np.sum((clean - noisy)**2)
    return 10 * np.log10(power_clean / power_noise)

# ===============================
# TEST PARAMETERS
# ===============================
test_file = "/content/sa1.wav"
clean_test, _ = librosa.load(test_file, sr=SR)
clean_test = clean_test[:SEGMENT_LEN]

# Fixed noise file for testing
noise_test, _ = librosa.load(noise_files[0], sr=SR)
noise_test = noise_test[:SEGMENT_LEN]

# SNRs to evaluate
test_snrs = [-5, 0, 5, 10, 15]

# Lists to store SNR results
snr_before = []
snr_after = []

# ===============================
# LOOP OVER SNR VALUES
# ===============================
plt.figure(figsize=(15, len(test_snrs) * 3))

for i, snr_val in enumerate(test_snrs):
    # Add noise at current SNR
    noisy_test = add_noise(clean_test, noise_test, snr_val)

    # Convert to spectrogram
    clean_spec = to_spectrogram(clean_test)
    noisy_spec = to_spectrogram(noisy_test)
    input_spec = noisy_spec[np.newaxis, ..., np.newaxis]

    # Predict denoised spectrogram
    predicted_spec = model.predict(input_spec, verbose=0)
    predicted_spec = predicted_spec[0, ..., 0]

    # Reconstruct audio from predicted magnitude + noisy phase
    phase = np.angle(librosa.stft(noisy_test, n_fft=N_FFT, hop_length=HOP_LENGTH))
    denoised_complex = np.expm1(predicted_spec) * np.exp(1j * phase)
    denoised_audio = librosa.istft(denoised_complex, hop_length=HOP_LENGTH)

    # Crop lengths to match clean signal
    min_len = min(len(clean_test), len(denoised_audio))
    clean_crop = clean_test[:min_len]
    denoised_crop = denoised_audio[:min_len]
    noisy_crop = noisy_test[:min_len]

    # Calculate SNR
    snr_in = calculate_snr(clean_crop, noisy_crop)
    snr_out = calculate_snr(clean_crop, denoised_crop)

    snr_before.append(snr_in)
    snr_after.append(snr_out)

    # Plot spectrograms
    plt.subplot(len(test_snrs), 3, i * 3 + 1)
    plt.imshow(noisy_spec, origin='lower', aspect='auto', cmap='viridis')
    plt.colorbar(format="%+2.0f dB")
    plt.title(f"Noisy (SNR={snr_val} dB)")

    plt.subplot(len(test_snrs), 3, i * 3 + 2)
    plt.imshow(predicted_spec, origin='lower', aspect='auto', cmap='viridis')
    plt.colorbar(format="%+2.0f dB")
    plt.title("Denoised")

    plt.subplot(len(test_snrs), 3, i * 3 + 3)
    plt.imshow(clean_spec, origin='lower', aspect='auto', cmap='viridis')
    plt.colorbar(format="%+2.0f dB")
    plt.title("Clean")

plt.tight_layout()
plt.show()

# ===============================
# PLOT SNR IMPROVEMENT
# ===============================
plt.figure(figsize=(6, 4))
plt.plot(test_snrs, snr_before, 'o-', label="Input SNR")
plt.plot(test_snrs, snr_after, 's-', label="Denoised SNR")
plt.xlabel("Input SNR (dB)")
plt.ylabel("SNR (dB)")
plt.title("CNN Denoising Performance")
plt.legend()
plt.grid(True)
plt.show()

